name: citymall
description: Grcoery App.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+2

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  get: ^4.6.6

  intl: ^0.18.1
  uuid: ^4.1.0
  flutter_svg: ^1.1.6
  flutter_screenutil: ^5.9.0
  device_preview: ^1.1.0
  carousel_slider: ^4.2.1

  dotted_border: ^2.1.0
  hive: ^2.2.3
  flutter_secure_storage: ^9.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.0
  pretty_http_logger: ^1.0.2

  awesome_dialog: ^3.1.0
  auto_size_text: ^3.0.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.0.4
  location_picker_flutter_map: ^2.0.0
  connectivity_plus: ^5.0.1

  flutter_otp_text_field: ^1.1.1
  tab_container: ^2.0.0
  flutter_html: ^3.0.0-beta.2

  location: ^5.0.3
  autoscale_tabbarview: ^1.0.2
  rolling_bottom_bar: ^0.2.2
  awesome_bottom_bar: ^1.2.4

  url_launcher: ^6.2.1

  length_unit: ^0.0.4
  timelines: ^0.1.0


  overlay_support: ^2.1.0
  mapmyindia_gl: ^0.3.2

  flutter_map_location_marker: ^8.0.2
  badges: ^3.1.2

  internet_connection_checker_plus: ^2.1.0
  flutter_email_sender: ^6.0.2
  otp_autofill: ^3.0.0
  telephony: ^0.2.0
  otp_text_field: ^1.1.3
  flutter_launcher_icons: ^0.13.1
  razorpay_flutter: ^1.3.5
  firebase_messaging: ^14.7.9
  firebase_core: ^2.24.2
  #  flutter_openmoney: ^0.0.2





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/
     - assets/icons/p_icon.svg
     - assets/images/no-image.jpg

flutter_launcher_icons:
  android: true

  image_path: "assets/images/app_icon.png"

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
